name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Generate the pacman contribution graph
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # 3. Create output directory and move the SVG
      - name: Prepare output
        run: |
          # Create output directory
          mkdir -p dist
          # Move the generated SVG to dist folder
          mv *.svg dist/ 2>/dev/null || echo "No SVG files found to move"
          # Check if file was created
          if [ -f "dist/pacman-contribution-graph.svg" ]; then
            echo "SVG file successfully created"
          else
            echo "Warning: SVG file was not generated"
            ls -la dist/ || true
          fi

      # 4. Deploy to output branch
      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
          keep_files: false
